importbin data/player.bin 0 2048 data.spr_plyr
importbin data/shadow.bin 0 128 data.spr_shdw
importbin data/bomb.bin 0 128 data.spr_bomb
importbin data/expl.bin 0 896 data.spr_expl
importbin data/block.bin 0 128 data.spr_blck
importbin data/crate.bin 0 128 data.spr_crate
importbin data/floor.bin 0 128 data.spr_floor
importbin data/pwrup_flame.bin 0 128 data.spr_pwrup_flame
importbin data/pwrup_bombs.bin 0 128 data.spr_pwrup_bombs
importbin data/font.bin 0 3072 data.spr_font
importbin data/palette.bin 0 48 data.palette
